# Generated by Django 5.2 on 2025-06-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_pendingbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
